use trivial;

INSERT INTO img_perfil (img) VALUES ('1.png');
INSERT INTO img_perfil (img) VALUES ('2.png');
INSERT INTO img_perfil (img) VALUES ('3.png');
INSERT INTO img_perfil (img) VALUES ('4.png');
INSERT INTO img_perfil (img) VALUES ('5.png');
INSERT INTO img_perfil (img) VALUES ('6.png');
INSERT INTO img_perfil (img) VALUES ('7.png');
INSERT INTO img_perfil (img) VALUES ('8.png');
INSERT INTO img_perfil (img) VALUES ('9.png');
INSERT INTO img_perfil (img) VALUES ('10.png');
INSERT INTO img_perfil (img) VALUES ('11.png');
INSERT INTO img_perfil (img) VALUES ('12.png');
INSERT INTO img_perfil (img) VALUES ('13.png');
INSERT INTO img_perfil (img) VALUES ('14.png');
INSERT INTO img_perfil (img) VALUES ('15.png');
INSERT INTO img_perfil (img) VALUES ('16.png');
INSERT INTO img_perfil (img) VALUES ('17.png');
INSERT INTO img_perfil (img) VALUES ('18.png');
INSERT INTO img_perfil (img) VALUES ('19.png');
INSERT INTO img_perfil (img) VALUES ('20.png');
INSERT INTO img_perfil (img) VALUES ('21.png');
INSERT INTO img_perfil (img) VALUES ('22.png');
INSERT INTO img_perfil (img) VALUES ('23.png');
INSERT INTO img_perfil (img) VALUES ('24.png');

INSERT INTO tema (tipo,img) VALUES ('Ciencia','ciencia.png');
INSERT INTO tema (tipo,img) VALUES ('Deporte','deporte.png');
INSERT INTO tema (tipo,img) VALUES ('Historia','historia.png');
INSERT INTO tema (tipo,img) VALUES ('Geografia','geografia.png');
INSERT INTO tema (tipo,img) VALUES ('Cultura','cultura.png');
INSERT INTO tema (tipo,img) VALUES ('Entretenimiento','entretenimiento.png');

INSERT INTO usuarios (nick,pass,email,admin,fk_img) VALUES ('admin','1234','admin@correo.es',true,1);
INSERT INTO usuarios (nick,pass,email,fk_img) VALUES ('CCoto','1234','carlos.coto.martin@alumnojoyfe.iepgroup.es',22);
INSERT INTO usuarios (nick,pass,email,fk_img) VALUES ('IMunnoz','1234','ismael.muñoz.masa@alumnojoyfe.iepgroup.es',23);
INSERT INTO usuarios (nick,pass,email,fk_img) VALUES ('AArribas','1234','alejandro.arribas.cantero@alumnojoyfe.iepgroup.es',24);

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue el primer presidente de la democracia española tras el franquismo?','Adolfo Suárez','Juan Carlos I','Pedro Sánchez','José Mª Aznar','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿La invasión de qué fortaleza por parte de los revolucionarios es considerada como el punto de inicio de la Revolución Francesa?','Bastilla','Waterloo','Roquetaillade','Castillo de los Duques de Bretaña','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué año el hombre pisó la Luna por primera vez?','1969','1989','1896','1945','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué evento se considera que desencadenó la Primera Guerra Mundial?','El asesinato del archiduque Francisco Fernando de Habsburgo','Invasión de Polonia por parte de los nazis','Invasión de las colonias alemanas en África por parte de los franceses','Invasión de las colonias francesas en África por parte de los alemanes','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿A partir de qué suceso consideramos que termina la Edad Antigua y empieza la Edad Media?','Caída del Imperio Romano de Occidente','Caída del Imperio Romano de Oriente','Descubrimiento de América','Reconquista','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue el primer presidente de Estados Unidos?','George Washington','Theodore Roosevelt','Abraham Lincoln','Thomas Jefferson','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuánto duró la Guerra de los Cien Años?','116 años','100 años','97 años','105 años','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué año se creó la Organización de las Naciones Unidas?','1945','1942','1947','1950','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué carabela no volvió del viaje en el que Colón arribó a América por primera vez?','La Santa María','La Pinta','La Niña','San Pedro','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la narración épica más antigua de la historia, encontrada en tablillas de arcilla sobre las que se usó escritura cuneiforme?','La Epopeya de Gilgamesh','La Iliada de Homero','La Epopeya de Homero','La Divina Comedia por Dante Alighieri','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el filósofo español conocido por su desarrollo de la teoría del cierre categorial?','Gustavo Bueno Martínez','José Ortega y Gasset','Fernando Savater','Miguel de Unamuno','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se apellidaban los dos exploradores que dieron la primera vuelta al mundo?','Magallanes-Elcano','Hesmanos Marx','Montgolfier','Hermanos Wright','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué faraón egipcio es conocido por haber intentado que su imperio pasase del politeísmo al monoteísmo a través del culto al dios Atón?','Akenatón','Tutankamon','Amenofis','Ramsés','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué emperador romano es conocido entre otras cosas por haber intentado someterse a operaciones de cambio de sexo?','Marco Aurelio Augusto','Julio César','Trajano','Mariciano','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué filósofo de la Antigua Grecia creía que el elemento del que están compuestas todas las cosas es el agua?','Tales de Mileto','Arquímedes','Pitágoras','Heráclito de Éfeso','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué idioma están escritos los manuscritos más antiguos pertenecientes a la parte de la Biblia que hoy conocemos como Nuevo Testamento?','Griego antiguo','Romano Antiguo','Arameo','Acadio','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién era el gran ministro británico cuando la India Británica fue sacudida por la hambruna de Bengala?','Winston Churchill','David Cameron','Anthony Eden','Clement Attlee','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué isla sirvió de prisión para Napoleón tras su derrota en la batalla de Waterloo?','Isla de Santa Elena','Isla de Ré','Isla de Noirmoutier','Isla de Levant','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué filósofo danés es considerado el principal precursor del existencialismo?','Søren Kierkegaard','Mikkel Borch-Jacobsen','Boecio de Dacia','Christian Eriksen','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quiénes fueron, según la leyenda, los dos hermanos fundadores de la ciudad de Roma?','Rómulo y Remo','Caca y Caco','Feronia y Feretrio','Roma y Rumina','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el fundador de la religión conocida como Movimiento de los Santos de los Últimos Días, asociados al Libro de Mormón?','Joseph Smith Jr','Michael James Sr','Dennis Robinson III','Robert Smith','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué líder militar africano se hizo conocido por usar una táctica de guerra llamada formación de cuernos de búfalo?','Shaka Zulú','Abdoul Raheem','Yacouba Sawadogo','Al Sisi','3');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Para qué religión es especialmente importante el rey Haile Selassie I?','Rastafari','Helenismo','Bahaísmo','Jainismo','3');

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el río más caudaloso del mundo?','Amazonas','Nilo','Congo','Orinoco','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el monte más alto del mundo?','Everest','K2','Kangchenjunga','Lhotse','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la lengua más hablada del mundo?','Chino Mandarín','Inglés','Español','Frances','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la línea vertical imaginaria a partir del cual se miden las longitudes y que divide el mundo en dos mitades?','Meridiano de Greenwich','Ecuador','Meridiano de Jackson','Horizonte ','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Dónde podemos encontrar la Casa Rosada?','Argentina','Marruecos','Brasil','México','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Entre qué países podemos encontrar el Estrecho de Bering?','EEUU y Rusia','Panamá y Costa Rica','Egipto y Jordania','Yibuti y Yemen','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la capital de Brasil?','Brasilia','Rio de Janeiro','Sao Paulo','Fortaleza','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el país de mayor tamaño del mundo?','Rusia','EEUU','China','Canada','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la capital de Nueva Zelanda?','Auckland','Wellington','Queenstown','Hamilton','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué cordillera separa Europa de Asia?','Urales','Andes','Cárpatos','Apeninos','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el nombre de la isla en la que vive la tribu no contactada menos conocida del mundo?','Sentinel del Norte','Palawan','Papúa Occidental','Sandwich del Sur','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la capital de Filipinas?','Manila','Dávao','Cebú','Quezon','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Además del alemán, el italiano y el francés, ¿qué otro idioma es hablado en ciertas regiones de Suiza?','Romache','Flamenco','Inglés','Español','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la capital de Mongolia?','Ulán Bator','Darjan','Ulaangom','Hovd','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el país europeo del que provienen las familias de la mayor parte de los habitantes de Argentina?','Italia','España','Portugal','Francia','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué país se habla mayoritariamente el idioma tagálog?','Filipinas','Malasia','Indonesia','Tailandia','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la capital de Letonia?','Riga','Daugavpils','Ventspils','Rēzekne','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la ciudad más poblada de África?','El Cairo','Lagos','Nairobi','Kinshasa','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el plato de puchero típico de Hungría hecho a partir de carne, cebolla y pimientos?','Gulash','Langos','Halaszle','Lecso','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el idioma de la Europa continental reconocido como una de las lenguas oficiales de Sudáfrica?','Afrikáans','Nenezo','Erzya','Komi','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué grupo étnico ha desarrollado una mitología en la que tiene mucha importancia el concepto de “Tiempo del Sueño”?','Aborígenes australianos','Aborígenes africanos','Aborígenes sudamericanos','Aborígenes asiaticos','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el nombre de la capital de Albania?','Tirana','Durrës','Vlorë','Sarandë','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué cordillera recorre el norte de Marruecos, Túnez y Argelia?','Atlas','Drakensberg','Lebombo','Mitumba','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el plato típico de la cocina rusa elaborado con bolas de carne picada envueltas en masa?','Pelmeni','Blini','Stroganoff ','Borsch','4');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué montaña es uno de los símbolos nacionales de Armenia?','Arabat','Aragats','Azhdahak Lerr','Nemrut','4');

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿A quién interpretaba John Travolta en “Grease”?','Danny Zuko','Kenickie','Mike','Balmudo','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué conocido cómico imitó a Hitler en la película “El Gran Dictador”?','Charles Chaplin','Buster Keaton','Roscoe Arbuckle','Ben Turpin','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue el director y a la vez protagonista de la película “Ciudadano Kane”?','Orson Welles','Joseph Cotten','William Alland','Everett Sloane','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue el famoso cantante del grupo musical Queen?','Freddie Mercury','Brian May','John Deacon','Roger Taylor','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la madre de Simba en la película de Disney “El Rey León”?','Sanabi','Nala','Mufasa','Sarafina','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la ciudad donde se encuentra el Mago de Oz?','Ciudad Esmeralda','Ciudad Diamante','Ciudad Rubi','Ciudad Amatista','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuáles fueron los tres primeros componentes de “Los payasos de la tele”?','Gaby, Fofó y Miliki','Gaby, Fofó y Rody','Gaby, Rody y Miliki','Rody, Fofó y Milikito','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿De qué grupo es la canción “Smells like a teen spirit”?','Nirvana','Led Zeppelin','Rolling Stones','Pink Floyd','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿A qué banda de música metal pertenece el disco Master of Puppets?','Metallica','The Who','Radiohead','U2','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Por qué película superventas de los años 90 es conocido el director y productor James Cameron?','Titanic','Avatar','Terminator','Aliens','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué película de Christopher Nolan narra la historia de un hombre con amnesia anterógrada, que no puede crear nuevos recuerdos a partir de lo que le va ocurriendo?','Memento','Interestellar','Inception','Tenet','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la protagonista de la saga de videojuegos "The Legend of Zelda"?','Link','Zelda','Rauru','Impa','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el protagonista de la serie de cómics The Sandman, de Neil Gaiman?','Morfeo','John Constantine','Hob Gadling','Lucifer','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué banda de rock latinoamericana adoptó en sus inicios el nombre de "Los Estereotipos"?','Soda Stereo','Café Tacvba','Fabulosos Cadillacs','Enanitos Verdes','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién es el guionista de la novela gráfica "Watchmen"?','Alan Moore','Marv Wolfman','Stan Lee','David Finch','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿A qué saga de películas pertenece el personaje conocido como Jack Sparrow?','Piratas del Caribe','Star Wars','Avatar','Red Sparrow','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué famoso dúo musical participó en la banda sonora de la película "Tron: Legacy"?','Daft Punk','Gorillaz','The Chemical Brothers','Stardust','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el protagonista de la serie de animación japonesa "Cowboy Bebop"?','Spike','Vicious','Ed','Jobim','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el antagonista principal de la película de Disney "El Rey León"?','Scar','Banzai','Ed','Shenzi','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué actor, guionista y monologuista inglés guionizó la versión británica de la serie "The Office"?','Ricky Gervais','Stephen Merchant','Karl Pilkington','David Earl','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué país transcurre la acción de la película "Chappie"?','Sudáfrica','EEUU','Reino Unido','Egipto','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué famoso youtuber hispanohablante tiene su propia serie de animación?','Rubius','Auronplay','Ibai','Willywex','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el manga de Kentaro Miura protagonizado por Guts (o Gatsu, en algunas traducciones)?','Berserk','Gigantomachia','Naruto','Bleach','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la práctica de quedarse tumbado boca abajo y manteniendo la rigidez del cuerpo, la cual se hizo viral a través de Internet mediante fotos y vídeos?','Planking','Lie Down','Planing','Aquaplaning','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el primer videojuego de la saga Donkey Kong que tenía imágenes en 3D?','Donkey Kong 64','Donkey Kong Land','Donkey Kong Country','Donkey Kong Jungle Beat','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el líder de los Autobots en "Transformers"?','Optimus Prime','Bumblebee ','Megatron','Ironhide','6');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué serie producida por Netflix tiene como uno de sus antagonistas principales una entidad llamada "Demogorgon"?','Stranger Things','Black Mirror','Insiders','Dark','6');

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién escribió la Ilíada y la Odisea?','Homero','No tiene autor reconocido','Gilgamesh','Sófocles','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué novela escribió Miguel de Cervantes y es considerada como una de los máximos exponentes de la literatura española y universal?','El ingenioso hidalgo Don Quijote de la Mancha','Novelas Ejemplares','La Galatea','La Gitanilla','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué gran artista es conocido por haber pintado la Capilla Sixtina?','Miguel Angel','Donatello','Rafaello','Leonardo Da Vinci','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién pintó el “Guernica”?','Pablo Picasso','Francisco de Goya','Diego Velázquez','Joan Miró','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿De qué estilo arquitectónico es la catedral de Notre Dame?','Gótico','Románico','Clásica','Contemporanea','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿De qué obra de Shakespeare forma parte el soliloquio “Ser o no ser, esa es la cuestión”?','Hamlet','Romeo y Julieta','Macbeth','Otelo','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién escribió “La colmena”?','Camilo José Cela','Miguel Delibes','Pío Baroja','Miguel de Unamuno','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué nombre tenía el caballo de Don Quijote de la Mancha?','Rocinante','Sardinilla','Bavieca','Antares','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué país fue considerado Gulliver un gigante durante sus viajes?','Liliput','Brobdingnag','Laputa','Houyhnhnms','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿De qué país es originario el tipo de poesía conocido como haiku?','Japón','China','Francia','Alemania','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué escritor hispanoparlante recibió el apodo de “el manco de Lepanto”?','Miguel de Cervantes','Francisco de Quevedo','Luis de Góngora','Lope de Vega','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué animal mitológico da nombre a uno de los libros más conocidos de Thomas Hobbes?','Leviatán','Hipogrifo','Minotauro','Fénix','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el famoso psicólogo estadounidense autor del libro “Más allá de la libertad y la dignidad”?','Burrhus Frederic Skinner','William James','Abraham Maslow','James Mark Baldwin','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el libro en el que se basa la película "Blade Runner"?','¿Sueñan los androides con ovejas eléctricas?','El hombre en el castillo','Ubik','Una mirada a la oscuridad','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el pintor noruego autor de la obra “El Grito”?','Edvard Munch','Christian Krohg','Erik Werenskiold','Eilif Peterssen','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('En la obra de fantasía de J. R. R. Tolkien, ¿qué nombre recibe el balrog que lucha contra Gandalf en el reino de Moria?','Daño de Durin','Lungorthin','Gothmog','Utumno','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué otro idioma, además del castellano, escribió la novelista y poetisa Rosalía de Castro?','Gallego','Catalán','Euskera','Inglés','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién escribió la novela “La Conjura de los Necios"?','John Kennedy Toole','Walker Percy','Flannery O´Connor','Stieg Larsson','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué continente nació Arya Stark, personaje de la saga de libros Canción de hielo y Fuego de George R. R. Martin?','Westeros','Sothoryos','Ulthos','Essos','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué personaje del universo literario de Harry Potter tiene una rata llamada Scabbers?','Ron Weasley','Draco Malfoy','Rubeus Hagrid','Neville Longbotton','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué película muda de ciencia ficción fue creada por Fritz Lang en 1927?','Metrópolis','Nosferatu','Viaje a la Luna','El nacimiento de una nación','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿De qué personaje ficticio estaba enamorado el Quijote?','Dulcinea','Dorotea','Marcela','Teresa Panza','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué pintor hizo el cuadro llamado “La joven de la perla”?','Johannes Vermeer','Rembrandt','Vincent van Gogh','Caravaggio','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué pianista y cantante de jazz compuso un álbum titulado “Glad Rag Doll”?','Diana Krall','Ella Fitzgerald','Billie Holiday','Sarah Vaughan','5');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('Qué poetisa de la Antigüedad hizo la obra “Oda a Afrodita”?','Safo de Mitilene','Corina','Cecilia Trebula','Julia Balbila','5');

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es la velocidad de la luz?','300.000.000 km/s','200.000.000 km/s','100.000.000 km/s','500.000.000 km/s','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué gas nos protege de la radiación solar, concretamente de la radiación ultravioleta, formando una capa en la atmósfera?','Ozono','Hidrógeno','Nitrógeno','Oxígeno','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el nombre técnico del miedo o fobia a las alturas?','Acrofobia','Aerofobia','Agorafobia','Cinofobia','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('La fórmula E=mc2, ¿en qué teoría científica aparece?','Teoría de la relatividad general','Teoría del todo','Teoría de supercuerdas','Teoría de cuerdas','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el ave de mayor envergadura que sigue viva actualmente?','Albatros','Cóndor de los Andes','Avestruz del norte de África','Buitre negro','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el principal tipo de célula que forma parte del sistema nervioso de humanos y otros animales?','Neurona','Eucariota','Procariota','Queratinocito','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Por qué fue famosa Marie Curie?','Descubrimiento de la radiactividad','Teoría de la evolución de las especies','Descubrimiento del átomo','Inventora de la imprenta','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el ave rapaz que se alimenta fundamentalmente de huesos?','Quebrantahuesos','Gallinazo Cabecinegro','Alimoche','Cuervo','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué especie de anfibio es conocida por su increíble capacidad para regenerar partes de su cuerpo que han sido dañadas o amputadas?','Ajolote','Lagartija','Lagarto','Sapo','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué especie de árbol de uso frecuente en la llamada medicina tradicional china es un ejemplo de fósil viviente por sus antiquísimos orígenes?','Gingko biloba','Abies fargesii','Ailanthus triphysa','Acer mandshuricum','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Alrededor de qué planeta orbitan los satélites Ganímedes, Calisto, Ío y Europa?','Jupiter','Saturno','Urano','Neptuno','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué archipiélago vive la única especie de cormorán que no es capaz de volar?','Galápagos','Antillas','Azores','Hawai','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Con qué denominación se conoce la línea dibujada por las estrellas Alnitak, Alnilam y Mintaka vistas desde nuestro planeta?','Cinturón de Orión','Cinturón de Kuiper','Cinturón de Van Allen','Cúmulo del Trapecio','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama la planta a partir de la cual suele ser elaborado el tequila?','Agave','Hyacinthus','Yucca','Dracaena','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el investigador que de manera paralela a Charles Darwin y por coincidencia desarrolló una teoría de la evolución casi idéntica a la del darwinismo?','Alfred Russell Wallace','Jean-Baptiste Lamarck','Gregor Mendel','Charles Lyell','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué nombre recibe el sistema de transcripción fonética usado en el chino mandarín?','Pinyin','Zhuyin','Jyutping','Rōmaji','1');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué período de la era paleozoica tuvo lugar entre el Devónico y el Pérmico?','Carbonífero','Cámbrico','Ordovícico','Silúrico','1');

INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuándo se celebró la primera Copa Mundial de Fútbol?','1930','1950','1920','1945','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue el campeón mundial de ajedrez entre los años 1972 y 1974, y el vencedor del “encuentro del siglo” contra el campeón soviético Boris Vasilievich Spassky?','Bobby Fischer','Boris Spassky','Gari Kaspárov','Anatoli Karpov','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién es considerado el mejor jugador de baloncesto de todos los tiempos?','Michael Jordan','Lebron James','Kobe Bryant','Larry Bird','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue la primera mujer en ganar una medalla olímpica?','Charlotte Cooper','Larisa Latynina','Lilí Álvarez','Gertrude Ederle','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué atleta tiene el record plusmarca de velocidad en los 100 metros lisos?','Usain Bolt','Tyson Gay','Yohan Blake','Asafa Powell','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cada cuántos años se celebran los Juegos Olímpicos?','2 años','4 años','3 años','5 años','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué equipo de fútbol ha ganado más Mundiales hasta el momento?','Brasil','Argentina','Alemania','Francia','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién fue Cobi?','La mascota de los Juegos Olimpicos de Barcelona','Un jugador de baloncesto de Los Angeles Lakers','Un pitcher de beisbol de los New York Yankees','El kicker de los Baltimore Ravens de la NFL','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué ajedrecista cubano fue campeón mundial de esta disciplina entre 1921 y 1927?','José Raúl Capablanca','Lázaro Bruzón','Leinier Domínguez','Yuniesky Quezada','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué ciudad española está el estadio de fútbol de Mestalla?',' Valencia','Bilbao','Sevilla','Zaragoza','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué tenista nacida en 1956 ganó 18 títulos de Grand Slam?','Martina Navrátilová','Margaret Court','Steffi Graf','Monica Seles','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué deporte jugado con un bate y una pelota es el más popular en la India?','Criquet','Béisbol','Sóftbol','Stoolball','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué ciudad nació el futbolista Lionel Messi?','Rosario','Buenos Aires','La Plata','Santa Fe','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Con qué mote se conoce al esquiador británico Michael Thomas Edwards?','Eddie the Eagle','Eddie the Captain','Super Eddie','Eddie the Miracle','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué jugador de golf nacido en la primera mitado del siglo XX cuenta con un mayor número de torneos majors ganados?','Jack Nicklaus','Arnold Palmer','Tom Watson','Gary Player','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el sobrenombre con el que se conoce al jugador profesional de Super Smash Bros. Jason Zimmerman?','M2K','JZ','Zimmmer','P4P','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué arte marcial de origen sudamericano fue desarrollado para parecerse a un baile?','Capoeira','Kenpo boliviano','Huka-huka','Kauto','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué jugador de fútbol dio pie a un movimiento conocido como la “gravesinha”?','Thomas Gravesen','Zinedine Zidane','Ronaldinho','Leo Messi','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué nadador de élite estadounidense ganó cuatro medallas de oro y dos de plata en los Juegos Olímpicos de Londres de 2012?','Michael Phelps','Caeleb Dressel','Mark Spitz','Michael Andrew','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué ciudad italiana nació el piloto de motociclismo Valentino Rossi?','Urbino','Maranello','Monza','Imola','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cómo se llama el videojuego de estrategia cuyos torneos tienen un seguimiento masivo en Corea del Sur desde finales de los 90?','StarCraft','World Of Warcraft','League Of Legends','Overwatch','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué deportista español se proclamó Campeón de las Series Mundiales de Ultra Runnning en tres años consecutivos de 2012 a 2014?','Kilian Jornet','Juan Pablo Montoya','Pastor Maldonado','Hayden Gullis','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué arte marcial es conocido como “el boxeo tailandés”?','Muay thai','Mongkhon','Muay Boran','Muay Lert Rit','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué equipo de fútbol estaba jugando David Beckham en el año 2007?','Los Ángeles Galaxy','Real Madrid',' París Saint-Germain','Milan','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué jugador de la NBA ha ganado más campeonatos?','Bill Russell','Wilt Chamberlain','Kareem Abdul Jabbar','Magic Johnson','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el piloto de MotoGP nacido en España que más campeonatos ha conseguido?','Marc Márquez','Dani Pedrosa','Jorge Lorenzo','Aleix Espargaró','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Quién es el único piloto de Fórmula 1 nacido en España que ha conseguido ganar el campeonato?','Fernando Alonso','Pedro Martinez de la Rosa','Marc Gené','Carlos Sainz','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿En qué franquicia de la NBA desarrolló toda su carrera profesional Kobe Bryant?','Los Angeles Lakers','Boston Celtics','New York Knicks','Chicago Bulls','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el tenista que ha ganado en más ocasiones el título de Roland Garros?','Rafael Nadal','Roger Fededer','Novak Djokovic','John McEnroe','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué futbolista, cuya demarcación era portero, pasó de jugar en el primer equipo del Fútbol Club Barcelona a probar suerte en el equipo de los Barcelona Dragons de fútbol americano?','Jesús Angoy','Arnau Tenas','José Manuel Pinto','Javier Urruti','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué conocido boxeador inició su trayectoria profesional con el nombre de Cassius Clay?','Muhammad Ali','Mike Tyson','Floyd Mayweather','Tyson Fury','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Cuál es el baloncestista más alto que ha participado en la ACB?','Christ Koumadje','Roberto Dueñas','Arvydas Sabonis','Walter Tavares','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué periodista deportivo popularizó la expresión "Jugón" para referirse a cracks tanto del fútbol como del baloncesto?','Andrés Montes','Julio Maldonado','Manolo Lama','Antoni Daimiel','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué futbolista argentino era apodado "El Conejito"?','Javier Saviola','Ángel Di María','Pablo Aimar','Juan Pablo Sorín','2');
INSERT INTO `preguntas_respuestas`(`pregunta`, `rcorrecta`, `rfalsa1`, `rfalsa2`, `rfalsa3`, `fk_tema`) VALUES ('¿Qué entrenador español logró el primer (y único) sextete al ganar los seis campeonatos posibles en una única temporada?','Josep Guardiola','Vicente del Bosque','Jose Luis Aragonés','Luis Enrique','2');



INSERT INTO partidas (player) VALUES ('CCoto');
INSERT INTO partidas (player) VALUES ('CCoto');
INSERT INTO partidas (player) VALUES ('CCoto');
INSERT INTO partidas (player) VALUES ('IMunnoz');
INSERT INTO partidas (player) VALUES ('IMunnoz');
INSERT INTO partidas (player) VALUES ('Imunnoz');
INSERT INTO partidas (player) VALUES ('AArribas');
INSERT INTO partidas (player) VALUES ('AArribas');
INSERT INTO partidas (player) VALUES ('AArribas');
INSERT INTO partidas (player) VALUES ('admin');


INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (5,10,1);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (5,1,2);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (4,2,2);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (4,3,2);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (3,4,3);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (3,5,3);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (2,6,3);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (2,7,4);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (1,8,4);
INSERT INTO leaderboard (puntuacion,fk_partida,fk_jugador) VALUES (1,9,4);
